version: '3.8'

services:
  backend:
    image: todo-task-manager-backend
    build:
      context: ./backend/TodoApi
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - todo-network

  frontend:
    image: todo-task-manager-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge