version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    # healthcheck:
    #   test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_password123 -Q "SELECT 1" || exit 1
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  backend:
    build:
      context: ./backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TodoDb;User=sa;Password=Your_password123;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    working_dir: /app
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  migrate:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /src/TodoApi
    volumes:
      - ./backend:/src
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=TodoDb;User=sa;Password=Your_password123;TrustServerCertificate=True;
    depends_on:
      - db
    entrypoint: >
      /bin/sh -c "dotnet tool install --global dotnet-ef &&
                  /root/.dotnet/tools/dotnet-ef database update"